### ISSUE TITLE
Error: nginx.conf file modified since installation

### ISSUE THREAD

**Issue by ericsnap** [sous-chefs/nginx#529]
## :ghost: Brief Description

I am getting an error when running `include_recipe nginx` on a box where I already ran it (several weeks ago):

```
Configuration file '/etc/nginx/nginx.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nginx.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package nginx (--configure):
 end of file on stdin at conffile prompt
```
I am trying to understand if this is something I am doing wrong or if it's normal behavior. I don't believe my cookbook or recipes are making any changes to `/etc/nginx/nginx.conf` itself. All I do is calling `nginx_site` later on to actually enable my site.

## :pancakes: Cookbook version

we're using version `8.1.2`

## :woman_cook:  Chef-Infra Version

we're using version `12.17.44`.

## :tophat: Platform details

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

## Steps To Reproduce

Not really any specific steps to reproduce per-se. I think my situation might happen when a new version of nginx gets released. 

Steps to (maybe) reproduce the behavior:

1. run the `nginx` recipe
1. create a site with `nginx_site`
1. wait until a new version of nginx is available
1. run the `nginx` recipe
1. this may display the error.

## :police_car: Expected behavior

if installing via `nginx` recipe, I would expect the process to _just work_. If I am modifying the `nginx.conf` file myself, my Chef recipe should re-apply whatever changes were made. Therefore, the recipe should for the clean `nginx.conf` file.

## :heavy_plus_sign: Additional context

We would like to upgrade to the latest versions of both Chef and nginx. If this was a known issue and was/is explicitly fixed in new versions of the package, I will push for an upgrade.
But if there is no expectations of an upgrade fixing the issue, I am reluctant to ask our deployment team to let us upgrade.

**Comment by damacus** [comment]
I highly recommend upgrading to the latest version of the cookbook, as these errors have been resolved.

**Comment by ericsnap** [comment]
@damacus thanks for the info. Yes, I believe this to be true. Although at the time of the writing, I had tried the latest version and was still seeing some issues. However, the root cause of the issue was that my IT team thought it was a good idea to manually force the install of `nginx` at whatever version came with the original Ubuntu 16.04. We had told them to _not_ install anything, we would do it as part of our code deploy.
Speaking of, maybe you can point me in the right direction, but I was under the impression this cookbook would always install the latest version of `nginx` when run. It seems to be true only if `nginx` was not already installed. Once installed, _is there an option in this cookbook to check for update and update if necessary?_

**Comment by damacus** [comment]
There isn't currently, but it would be good to figure out a way to upgrade it. Without looking at the code, I'm assuming that the check doesn't include the version, just the fact that nginx is on disk. 

If you want to look at upgrades that's probably where to start. This is definitely an issue worth raising if you don't mind? 


Thanks
Dan
